#!/bin/bash
#===============================================================================
# TEST SSH KEY FORMAT
#
# This script helps verify your SSH key is in the correct format
#===============================================================================

echo "==============================================================================="
echo "SSH KEY FORMAT CHECKER"
echo "==============================================================================="
echo ""
echo "Your VPS_SSH_KEY secret should look EXACTLY like this:"
echo ""
echo "-----BEGIN OPENSSH PRIVATE KEY-----"
echo "b3BlbnNzaC1rZXktdjEAAAAABG5vbmUAAAAEbm9uZQAAAAAAAAABAAAAMwAAAAtzc2gtZW"
echo "QyNTUxOQAAACDxKt6T8Qs5..."
echo "(many more lines)"
echo "-----END OPENSSH PRIVATE KEY-----"
echo ""
echo "==============================================================================="
echo "COMMON MISTAKES:"
echo "==============================================================================="
echo ""
echo "❌ Missing BEGIN/END lines"
echo "❌ Extra spaces or newlines"
echo "❌ Using PUBLIC key instead of PRIVATE key"
echo "❌ Copy-paste formatting issues"
echo ""
echo "==============================================================================="
echo "TO GET THE CORRECT KEY:"
echo "==============================================================================="
echo ""
echo "1. SSH into your server:"
echo "   ssh deploy@YOUR_SERVER_IP"
echo ""
echo "2. Run this command:"
echo "   cat ~/.ssh/id_ed25519"
echo ""
echo "3. Copy the ENTIRE output (use mouse selection)"
echo ""
echo "4. Paste into GitHub Secret (do NOT add any extra characters)"
echo ""
echo "==============================================================================="
echo "VERIFY KEY EXISTS ON SERVER:"
echo "==============================================================================="
echo ""
echo "SSH to your server and run:"
echo "  ls -la ~/.ssh/id_ed25519"
echo ""
echo "Should show something like:"
echo "  -rw------- 1 deploy deploy 464 Jan 25 00:00 /home/deploy/.ssh/id_ed25519"
echo ""
echo "If file doesn't exist, run the setup script again."
echo ""
